import type { Metadata } from "next";
import ReduxProvider from "@/app/Redux/ReduxProvider";
import { Navbar, Footer, Login, Signup } from './components'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Navbar />
          <Login />
          <Signup />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
